export const TopBarWideStyles = {
    TopBarContainer: {
        borderBottomColor: 'lightgrey',
        borderBottomWidth: 1,
        paddingBottom: '1rem',
    },
    TopRowContainer: {
        flexDirection: 'row',
        display: 'flex',
        justifyContent: 'space-between',
    },
    LogoLink: {
        display: "flex",
        color: '#FF385C',
        justifyContent: 'center',
        alignItems: 'center',
        paddingLeft: '.5rem'
    },
    SearchBoxContainer: {
        flexDirection: 'row',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
    },
    SearchBoxLeftBtn: {
        borderTopLeftRadius: 30,
        borderBottomLeftRadius: 30,
        borderTopWidth: 1,
        borderBottomWidth: 1,
    },
    SearchBoxLeftBtnText: {
        margin: '.75rem',
        borderRightWidth: 2,
        paddingRight: '.75rem',
        paddingLeft: '.75rem',
    },
    SearchBoxMidBtn: {
        borderTopWidth: 1,
        borderBottomWidth: 1,
        padding: '.75rem',
    },
    SearchBoxRightBtn: {
        borderTopRightRadius: 30,
        borderBottomRightRadius: 30,
        borderTopWidth: 1,
        borderBottomWidth: 1,
    },
    SearchBoxRightBtnDiv: {
        margin: '.65rem',
        borderLeftWidth: 2,
        paddingLeft: '.75rem',
        color: 'lightgrey',
        flexDirection: 'row',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
    },
    SearchBoxSearchIcon: {
        marginLeft: '.75rem',
        borderRadius: 50,
        backgroundColor: '#FF385C',
        padding: '.45rem',
        width: 13,
        height: 13,
    },
    TopBarRightContainer: {
        flexDirection: 'row',
        display: 'flex',
    },
    TopBarRightBtn: {
        paddingLeft: '1rem',
        paddingRight: '1rem',
        borderRadius: '2rem',
    },
    UserBtn: {
        justifyContent: 'center',
        alignItems: 'center',
        display: 'flex',
        borderRadius: '4rem',
        borderWidth: 1,
        paddingLeft: '.5rem',
        paddingRight: '.5rem',
        marginLeft: '.5rem',
    },
    UserIcon: {
        marginLeft: '.75rem',
        backgroundColor: 'lightgrey',
        color: 'white',
        padding: '.5rem',
        borderRadius: 40,
        width: 15,
    },

    AdvancedSearchContainer: {
        flexDirection: 'row',
        display: 'flex',
        justifyContent: 'center',
    },
    AdvancedSearchBox: {
        marginTop: '1rem',
        display: 'flex',
    },
    AdvancedSearchBoxLeftBtn: {
        borderTopLeftRadius: 30,
        borderBottomLeftRadius: 30,
        borderWidth: 1,
        padding: '.75rem',
        display: 'flex',
        borderRightColor: 'transparent',
        justifyContent: 'center',
        flexDirection: 'column',
        paddingLeft: '2rem',
        width: '15rem',
    },
    AdvancedSearchBoxMiddleBtn: {
        borderWidth: 1,
        padding: '.75rem',
        display: 'flex',
        justifyContent: 'center',
        flexDirection: 'column',
        paddingLeft: '2rem',
        paddingRight: '2rem',
        borderLeftColor: 'transparent',
        borderRightColor: 'transparent',
    },
    AdvancedSearchBoxRightBtn: {
        borderWidth: 1,
        padding: '.75rem',
        display: 'flex',
        justifyContent: 'space-between',
        flexDirection: 'row',
        borderTopRightRadius: 30,
        borderBottomRightRadius: 30,
        width: '20rem',
        paddingLeft: '.75rem',
        paddingRight: '.75rem',
        alignItems: 'center',
        borderLeftColor: 'transparent',
    },
    AdvancedSearchBoxTitle: {
        fontSize: '.75rem',
    },
    AdvancedSearchBoxSubTitle: {
        color: 'grey',
        fontSize: '.85rem',
    },
    AdvancedSearchBoxSeaprateLine: {
        borderColor: 'lightgrey',
        borderRightWidth: 1,
        marginTop: '1.2rem',
        marginBottom: '1.2rem',
    },
    AdvancedSearchBoxRightBtnLeftContainer: {
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'flex-start',
        alignItems: 'flex-start',
    },
    AdvancedSearchBoxSearchBtn: {
        backgroundColor: '#FF385C',
        borderRadius: 60,
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
        padding: '.75rem',
    },
    AdvancedSearchBoxSearchBtnText: {
        color: 'white',
        marginLeft: '.75rem',
    },

    SearchTypeBtn: {
        padding: '1rem',
        paddingBottom: '.75rem',
        borderBottomColor: 'black',
    },
}